In [1]:
import pandas as pd   
import numpy as np
import matplotlib.pyplot as plt  
import seaborn as sns

%matplotlib inline

In [2]:
teis_monthly_df = pd.read_csv('../data/teis_monthy_referral.csv')

teis_monthly_df

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification/ Referral Date,Parent Consent Date,...,Service Coordinator Counter,Fiscal Year.1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
0,ET,403339,8/9/2014,Blount,Transitional,Eligibility,A,Kristi Borer,7/1/2016,7/1/2016,...,1,2016,1,NaN,NaN,8/9/2017,NaN,1,Qtr 1,#REF!
1,FT,404085,7/31/2013,Unicoi,At-Risk,Notification,I,Jennifer Terranera - 45 days,7/1/2016,NaN,...,1,2016,1,NaN,NaN,7/31/2016,1.0,1,Qtr 1,#REF!
2,FT,403623,2/5/2016,Sullivan,Transitional,Eligibility,A,Amy Talbert,7/1/2016,7/20/2016,...,1,2016,1,NaN,NaN,2/5/2019,NaN,1,Qtr 1,#REF!
3,FT,404157,12/6/2015,Sullivan,Transitional,IFSP,A,Candice Cradic,7/1/2016,7/22/2016,...,1,2016,1,NaN,NaN,12/6/2018,NaN,1,Qtr 1,#REF!
4,FT,404154,4/18/2015,Hawkins,At-Risk,IFSP,A,Kathy Jeffries,7/1/2016,7/18/2016,...,1,2016,1,NaN,NaN,4/18/2018,NaN,1,Qtr 1,#REF!
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113251,UC,528759,4/7/2021,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,5/16/2022,5/26/2022,...,1,2021,1,NaN,NaN,4/7/2024,NaN,4,Qtr 4,#REF!
113252,UC,528534,3/13/2022,Sumner,Competitive,IFSP,A,Robyn Hogan,5/11/2022,5/23/2022,...,1,2021,1,NaN,NaN,3/13/2025,NaN,4,Qtr 4,#REF!
113253,UC,528430,1/5/2022,Cumberland,Transitional,Eligibility,A,Lisa Davis,5/10/2022,5/18/2022,...,1,2021,1,NaN,NaN,1/5/2025,NaN,4,Qtr 4,#REF!
113254,UC,528253,9/12/2020,Sumner,Competitive,IFSP,A,Taylor Lee,5/6/2022,5/11/2022,...,1,2021,1,NaN,NaN,9/12/2023,NaN,4,Qtr 4,#REF!
113255,UC,528535,2/8/2022,Smith,Transitional,Evaluation,A,Sherry Roberts-DS,5/11/2022,5/27/2022,...,1,2021,1,NaN,NaN,2/8/2025,NaN,4,Qtr 4,#REF!

In [3]:
teis_referral_df = pd.read_csv('../data/teis_referral.csv')

teis_referral_df

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification Date,Parent Consent Date,Referral Source Type Name,Initial Eligibility,Initial Eligibility Date,Initial IFSP Date,Latest IFSP Date,Exit Reason,Exit Date
0,ET,411812,12/14/2016,Blount,Transitional,Notification,I,Charity Decker,12/16/2016,NaN,DCS,NaN,NaN,NaN,NaN,Unable to contact,12/29/2016
1,ET,417398,4/6/2015,Knox,Transitional,Eligibility,I,Jackie Campbell,4/24/2017,5/2/2017,Parent,Ineligible,5/16/2017,NaN,NaN,Ineligible for Part C,5/16/2017
2,ET,419400,3/4/2016,Roane,Transitional,Notification,I,Kelly Brackney,6/6/2017,NaN,DCS,NaN,NaN,NaN,NaN,Parent decline,6/30/2017
3,ET,397571,5/11/2015,Knox,Transitional,Eligibility,I,Wendy Burton,5/24/2017,6/13/2017,Other,Ineligible,6/16/2017,NaN,NaN,Ineligible for Part C,6/16/2017
4,ET,404648,9/23/2015,Knox,Transitional,IFSP,I,Sarah Scott,7/18/2016,7/28/2016,Other,Eligible,8/1/2016,8/16/2016,7/24/2018,618 - Part B eligibility not determined,9/21/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96575,UC,519094,4/10/2020,Macon,Transitional,Eligibility,I,Sherry Roberts-DS,1/12/2022,1/19/2022,PCP,Ineligible,1/31/2022,NaN,NaN,Ineligible for Part C,1/31/2022
96576,UC,528253,9/12/2020,Sumner,Competitive,IFSP,A,Taylor Lee,5/6/2022,5/11/2022,PCP,Eligible,5/23/2022,5/31/2022,5/31/2022,NaN,NaN
96577,UC,525460,8/27/2019,Sumner,Competitive,Notification,I,Sherry Roberts-DS,3/29/2022,NaN,PCP,NaN,NaN,NaN,NaN,Unable to contact,4/11/2022
96578,UC,528535,2/8/2022,Smith,Transitional,Evaluation,A,Sherry Roberts-DS,5/11/2022,5/27/2022,Parent,NaN,NaN,NaN,NaN,NaN,NaN
96579,UC,514216,2/4/2021,Sumner,Competitive,IFSP,I,Dawn Reed,11/5/2021,11/10/2021,PCP,Eligible,12/1/2021,12/7/2021,12/7/2021,618 - Parent withdraw,2/10/2022

In [4]:
teis_monthly_df.value_counts('Child ID').head(15267)

Child ID
452977    7
471335    7
480297    7
447124    7
437882    6
         ..
471704    2
414503    2
414382    2
462658    2
414876    2
Length: 15267, dtype: int64

In [5]:
teis_referral_df.value_counts('Child ID').head()

Child ID
104085    1
487945    1
487955    1
487953    1
487952    1
dtype: int64

In [7]:
#teis_monthly_df = teis_monthly_df.drop(columns=['Referral Source Category',
#                                                'Qtr',
#                                                'Child Count',
#                                                '2013 Child Count',
#                                                '2012 Child Count',
#                                                'Service Coordinator Counter'])

In [8]:
teis_monthly_df

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification/ Referral Date,Parent Consent Date,...,Service Coordinator Counter,Fiscal Year.1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
0,ET,403339,8/9/2014,Blount,Transitional,Eligibility,A,Kristi Borer,7/1/2016,7/1/2016,...,1,2016,1,NaN,NaN,8/9/2017,NaN,1,Qtr 1,#REF!
1,FT,404085,7/31/2013,Unicoi,At-Risk,Notification,I,Jennifer Terranera - 45 days,7/1/2016,NaN,...,1,2016,1,NaN,NaN,7/31/2016,1.0,1,Qtr 1,#REF!
2,FT,403623,2/5/2016,Sullivan,Transitional,Eligibility,A,Amy Talbert,7/1/2016,7/20/2016,...,1,2016,1,NaN,NaN,2/5/2019,NaN,1,Qtr 1,#REF!
3,FT,404157,12/6/2015,Sullivan,Transitional,IFSP,A,Candice Cradic,7/1/2016,7/22/2016,...,1,2016,1,NaN,NaN,12/6/2018,NaN,1,Qtr 1,#REF!
4,FT,404154,4/18/2015,Hawkins,At-Risk,IFSP,A,Kathy Jeffries,7/1/2016,7/18/2016,...,1,2016,1,NaN,NaN,4/18/2018,NaN,1,Qtr 1,#REF!
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113251,UC,528759,4/7/2021,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,5/16/2022,5/26/2022,...,1,2021,1,NaN,NaN,4/7/2024,NaN,4,Qtr 4,#REF!
113252,UC,528534,3/13/2022,Sumner,Competitive,IFSP,A,Robyn Hogan,5/11/2022,5/23/2022,...,1,2021,1,NaN,NaN,3/13/2025,NaN,4,Qtr 4,#REF!
113253,UC,528430,1/5/2022,Cumberland,Transitional,Eligibility,A,Lisa Davis,5/10/2022,5/18/2022,...,1,2021,1,NaN,NaN,1/5/2025,NaN,4,Qtr 4,#REF!
113254,UC,528253,9/12/2020,Sumner,Competitive,IFSP,A,Taylor Lee,5/6/2022,5/11/2022,...,1,2021,1,NaN,NaN,9/12/2023,NaN,4,Qtr 4,#REF!
113255,UC,528535,2/8/2022,Smith,Transitional,Evaluation,A,Sherry Roberts-DS,5/11/2022,5/27/2022,...,1,2021,1,NaN,NaN,2/8/2025,NaN,4,Qtr 4,#REF!

In [39]:
childid_df = teis_monthly_df.groupby(by=["Child ID"]).sum()

In [36]:
teis_df.value_counts("Child ID").head()

Child ID
104085    1
486501    1
486510    1
486509    1
486508    1
dtype: int64

In [37]:
#teis_df.value_counts("Child ID").head()

In [38]:
teis_df

,Referral Count,Evaluation Count,Eligibility Count,IFSP Count,Service Coordinator Counter,Fiscal Year.1,Child Count,2012 Child Count,2013 Child Count,Late Referral,Qtr
Child ID,,,,,,,,,,,
104085,1,0.0,0.0,0.0,1,2017,1,0.0,0.0,1.0,3
350065,1,1.0,0.0,0.0,1,2016,1,0.0,0.0,1.0,1
351755,1,1.0,0.0,0.0,1,2016,1,0.0,0.0,0.0,1
353800,1,0.0,0.0,0.0,1,2016,1,0.0,0.0,1.0,1
353805,1,1.0,0.0,0.0,1,2016,1,0.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...
529587,1,1.0,0.0,0.0,1,2021,1,0.0,0.0,0.0,4
529597,1,0.0,0.0,0.0,1,2021,1,0.0,0.0,0.0,4
529599,1,0.0,0.0,0.0,1,2021,1,0.0,0.0,1.0,4
529606,1,0.0,0.0,0.0,1,2021,1,0.0,0.0,0.0,4
529609,1,0.0,0.0,0.0,1,2021,1,0.0,0.0,0.0,4

In [ ]:
#teis_df = pd.concat([teis_monthly_df, teis_referral_df])

In [ ]:
#teis_df

In [ ]:
#teis_df.value_counts('Child ID').head(10000)

In [ ]:
#teis_df = pd.merge(teis_monthly_df, teis_referral_df, 
#                               left_on = 'Child ID', right_on = 'Child ID', 
#                               how = 'inner')
#teis_df

In [ ]:
#teis_df.value_counts('Child ID').head()

In [ ]:
#dict1 = {'Child ID':[2,2,3,4,5]}
#dict2 = {'Child ID':[2,2,3,4,5]}

#teis_monthly_df = pd.DataFrame.reset_index()
#teis_referral_df = pd.DataFrame.reset_index()

#teis_df = teis_monthly_df.merge(teis_referral_df, on = 'Child ID')
#teis_df = pd.DataFrame(teis_df[teis_df.index_x==teis_df.index_y]['Child ID'], columns=['Child ID']).reset_index(drop=True)
#teis_df